myFinance/myFinance/Models/myFinanceUserModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace myFinance.Models
{
    public class myFinanceUserModel
    {
        [Key]
        [EmailAddress]
        [StringLength(150)]
        [Display(Name = "Email : ")]
        [Required(ErrorMessage = "Email is required.")]
        [RegularExpression(@"^\w+([-+.']\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*$")]
        public string Email { get; set; }

        [Required(ErrorMessage = "Introduceti numele.")]
        [StringLength(20, MinimumLength = 6, ErrorMessage = "Introduceti intre 6 si 20 de caractere.")]
        [Display(Name = "Nume : ")]
        public string Nume { get; set; }

        [Required(ErrorMessage = "Introduceti prenumele.")]
        [StringLength(20, MinimumLength = 6, ErrorMessage = "Introduceti intre 6 si 20 de caractere.")]
        [Display(Name = "Prenume : ")]
        public string Prenume { get; set; }

        [Required]
        [DataType(DataType.Password)]
        [StringLength(20, MinimumLength = 6, ErrorMessage = "Introduceti intre 6 si 20 de caractere.")]
        [Display(Name = "Parola: ")]
        public string Parola { get; set; }

        [Required]
        [DataType(DataType.Password)]
        [StringLength(20, MinimumLength = 6,ErrorMessage = "Introduceti intre 6 si 20 de caractere.")]
        [Display(Name = "Confirma parola: ")]
        public string ConfirmaParola { get; set; }

    }
}

myFinance/myFinance/Controllers/AdministratorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace myFinance.Controllers
{
    public class AdministratorController : Controller
    {
        // GET: Administrator
        public ActionResult Index()
        {
            return View();
        }
    }
}

myFinance/myFinance/Controllers/LogatController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace myFinance.Controllers
{
    public class LogatController : Controller
    {
        // GET: Logat
        public ActionResult Index()
        {
            return View();
        }
         
    }
}

myFinance/myFinance/Controllers/RegistrationLoginController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace myFinance.Controllers
{
    public class RegistrationLoginController : Controller
    {
        public ActionResult Index()
        {
            return View();
        } 
        [HttpGet]
        public ActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Register(Models.myFinanceUserModel user)
        {

            if (ModelState.IsValid)
            {
                using (var db = new myFinanceDatabaseEntities())
                {

                    var usercontainer = db.myFinanceUsers.Create();

                    usercontainer.Email = user.Email;
                    usercontainer.Nume = user.Nume;
                    usercontainer.Prenume = user.Prenume;
                    usercontainer.Parola = user.Parola;
                    usercontainer.ConfirmaParola = user.ConfirmaParola;
                    if (user.Parola == user.ConfirmaParola)
                    {
                        //se verifica daca mai exista un email introdus in baza de date
                        var count = db.myFinanceUsers.Count(u => u.Email == user.Email);
                        if (count == 0)
                        {
                            //se adauga userul in DB
                            db.myFinanceUsers.Add(usercontainer);
                            db.SaveChanges();

                            ViewBag.Successful = user.Email +
                                                 " te-ai inregistrat cu succes. Daca doresti sa accesezi site-ul Logheaza-te.";
                            return RedirectToActionPermanent("Index");
                        }
                        {

                            ViewBag.EroareEmail = "Adresa de email introdusa: " + user.Email +
                                                  " exista deja in baza de date. Inregistrati-va cu alt user";
                            return View("Register");
                        }
                    }
                    {
                        ViewBag.EroareParole = "Campurile: Parola si confirma parola trebuie sa fie identice. ";
                        return View("Register");
                    }
                }
            }
            {
                ModelState.AddModelError("", "Inregistrarea nu s-a putut realiza.");
            }
            return View();
        }

        [HttpGet]
        public ActionResult LogIn()
        {
            return View();
        }

        [HttpPost]
        public ActionResult LogIn(Models.myFinanceUserModel user)
        {
            
                using (var db = new myFinanceDatabaseEntities())
                {
                    var admin =
                        db.myFinanceUsers.FirstOrDefault(
                            u => u.Email == user.Email && u.Parola == user.Parola && u.RoluriUser == "Administrator");
                    if (admin != null)
                    {
                    Session["Logat"] = "Logat cu email: " + user.Email;
                    return RedirectToAction("Index", "Administrator");}
                {  

                    var usr = db.myFinanceUsers.FirstOrDefault(u => u.Email == user.Email && u.Parola == user.Parola);
                    if (usr != null)
                    {
                        Session["Logat"] = "Logat cu email: " + user.Email;
                        return RedirectToAction("Index", "Logat");
                    }
                    {
                        ViewBag.EroareLogare = "Datele introduse nu sunt corecte. Logarea nu s-a produs. Va rugam introduceti datele din nou!";
                        return View();
                    }
                }
            }
            } 

        public ActionResult Logout()
        {
            FormsAuthentication.SignOut();
            Session.Abandon();
            return RedirectToAction("Index");
        } 
    }
}

myFinance/myFinance/Views/Administrator/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Administrator/_Layout.cshtml";
}

<h2>Index din administrator page(view)</h2>

myFinance/myFinance/Views/Administrator/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - myFinance Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css"/> 
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top cls">
        <div class="container cls" >
            <div class="navbar-header cls">
                <button type="button" class="navbar-toggle cls" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar cls"></span>
                    <span class="icon-bar cls"></span>
                    <span class="icon-bar cls"></span>
                </button>
                
                
            </div>
            <div class="navbar-collapse collapse cls">
                <ul class="nav navbar-nav cls">
                    <li style="color:lightblue">myFinance</li> 
                    @if (Session["Logat"] != null)
                    {
                        <li style="color: red">
                            <h4>Urmeaza a fi puse butoane specifice paginii de aministrator</h4></li>
                        <li id="signOutAdmin">
                            @using (Html.BeginForm("Logout", "RegistrationLogin"))
                            {
                                <button type="submit" class="butoane"> Logout </button>
                            }
                        </li>
                    } 
                </ul>
            </div>
        </div>
    </div>

<div class="container body-content">
    @ViewBag.Message
    @RenderBody()
    <hr/>
    <footer class="cls">
        <p>&copy; @DateTime.Now.Year - myLogin</p>
    </footer>
</div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

myFinance/myFinance/Views/Logat/Index.cshtml
@model myFinance.myFinanceUser

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Logat/_Layout.cshtml";
}

<h2>Index de la view-ul LOGAT</h2>

 
 

myFinance/myFinance/Views/Logat/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - myFinance Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css"/> 
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top cls">
        <div class="container cls" >
            <div class="navbar-header cls">
                <button type="button" class="navbar-toggle cls" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar cls"></span>
                    <span class="icon-bar cls"></span>
                    <span class="icon-bar cls"></span>
                </button>
                
                
            </div>
            <div class="navbar-collapse collapse cls">
                <ul class="nav navbar-nav cls">
                    <li style="color:lightblue">myFinance</li>
                     
                    @if (Session["Logat"] != null)
                    { 
                        @*<li>@Html.ActionLink("Acasa", "Index", "Logat")</li>
                        <li>@Html.ActionLink("Venituri", "Index", "Logat")</li>
                        <li>@Html.ActionLink("Cheltuieli", "Index", "Logat")</li>
                        <li>@Html.ActionLink("Grafice", "Index", "Logat")</li>*@
                        @*<li id="signOut">@Html.ActionLink("LogOut", "Logout", "RegistrationLogin")</li>*@

                        @*La formul de mai jos Html.BeginForm("Index", "Logat") exprima actiune si controller*@
                        <li>
                            @using (Html.BeginForm("Index", "Logat")) 
                            {
                                <button type="submit" class="butoane">Acasa</button>
                            }
                        </li>
                        <li>
                            @using (Html.BeginForm("Index", "Logat"))  
                            {
                                <button type="submit" class="butoane">Venituri</button>
                            }
                        </li>
                        <li>
                            @using (Html.BeginForm("Index", "Logat"))  
                            {
                                <button type="submit" class="butoane">Cheltuieli</button>
                            }
                        </li>
                        <li>
                            @using (Html.BeginForm("Index", "Logat"))  
                            {
                                <button type="submit" class="butoane">Grafice</button>
                            }
                        </li>
                        <li id="signOut">
                            @using (Html.BeginForm("Logout", "RegistrationLogin"))
                            {
                                <button type="submit" class="butoane"> Logout </button>
                            }
                        </li>
                    }
                     
                </ul>
            </div>
        </div>
    </div>

<div class="container body-content">
    @ViewBag.Message
    @RenderBody()
    <hr/>
    <footer class="cls">
        <p>&copy; @DateTime.Now.Year - myLogin</p>
    </footer>
</div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

myFinance/myFinance/Views/RegistrationLogin/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

 <h3 class="cls">Welcome to myFinance Application</h3>
<p style="background-color: red">@ViewBag.Successful</p>

myFinance/myFinance/Views/RegistrationLogin/Login.cshtml
@model myFinance.myFinanceUser

@{
    ViewBag.Title = "Login";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Autentifica-te</h2>
<div class="error">
    @ViewBag.EroareDeState
    @ViewBag.EroareLogare
</div>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
         
        <hr/>
        @Html.ValidationSummary(true, "", new {@class = "text-danger"})
        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.Email, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Parola, htmlAttributes: new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.Parola, new {htmlAttributes = new {@class = "form-control", type="password"}})
                @Html.ValidationMessageFor(model => model.Parola, "", new {@class = "text-danger"})
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Login" class="btn btn-default"/>
            </div>
        </div>
    </div>

}
 

myFinance/myFinance/Views/RegistrationLogin/Register.cshtml
@model myFinance.myFinanceUser
@{ Html.EnableClientValidation(true); }
@{
    ViewBag.Title = "Register";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Inregistreaza-te</h2>
<p class="error">@ViewBag.EroareParole</p>
<p class="error">@ViewBag.EroareEmail</p>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger " })
        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new {htmlAttributes = new {@class = "form-control editor"}})
            </div>
            <span>@Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger " })</span>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nume, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nume, new { htmlAttributes = new { @class = "form-control editor" } })
                @Html.ValidationMessageFor(model => model.Nume, "", new { @class = "text-danger " })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Prenume, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Prenume, new { htmlAttributes = new { @class = "form-control editor" } })
                @Html.ValidationMessageFor(model => model.Prenume, "", new { @class = "text-danger " })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Parola, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Parola, new { htmlAttributes = new { @class = "form-control editor", type = "password" } })
                @Html.ValidationMessageFor(model => model.Parola, "", new { @class = "text-danger " })
            </div>
        </div>

        <div class="form-group">
        <span style="font-weight: bold" class ="control-label col-md-2">Confirma&nbsp;parola</span>
            @*@Html.LabelFor(model => model.ConfirmaParola, htmlAttributes: new {@class = "control-label col-md-2"})*@
            <div class="col-md-10">
                @Html.EditorFor(model => model.ConfirmaParola, new {htmlAttributes = new {@class = "form-control editor", type="password"}})
                @Html.ValidationMessageFor(model => model.ConfirmaParola, "", new {@class = "text-danger " })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Inregistreaza-te" class="btn btn-default editor" />
            </div>
        </div>
    </div>
}

 

myFinance/myFinance/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - myFinance Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top cls">
        <div class="container cls">
            <div class="navbar-header cls">
                <button type="button" class="navbar-toggle cls" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar cls"></span>
                    <span class="icon-bar cls"></span>
                    <span class="icon-bar cls"></span>
                </button>


            </div>
            <div class="navbar-collapse collapse cls">
                <ul class="nav navbar-nav cls">
                    <li style="color:lightblue">myFinance</li>
                    @*<li>@Html.ActionLink("Register", "Register", "RegistrationLogin", null, new { @class = "butoane" })</li>
                    <li>@Html.ActionLink("Login", "Login", "RegistrationLogin",null, new { @class = "butoane" })</li>*@

                    @if(Session["Logat"] != null) {
                    <li id="signOut">
                        @using (Html.BeginForm("Logout", "RegistrationLogin"))
                        {
                            <button type="submit" class="butoane"> Logout </button>
                        }
                    </li>
                    }
                    else
                    {
                    <li>@using (Html.BeginForm("Register", "RegistrationLogin", FormMethod.Get))
                        {<button type="submit" method="GET" class="butoane">Register</button>}</li>
                    <li>@using (Html.BeginForm("Login", "RegistrationLogin", FormMethod.Get))
                    {<button type="submit" method="GET" class="butoane">Login</button>}</li>
                    }
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @ViewBag.Message
        @RenderBody()
        <hr />
        <footer class="cls">
            <p>&copy; @DateTime.Now.Year - myFinance</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>